// @ts-nocheck
import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { toast } from 'sonner';
import { fetchVehicleFinanceSettings, postVehiclePaymentToGL, NCG_HOLDING_ID } from '@/hooks/useVehicleSalesFinance';

export interface LightVehicleOrder {
  id: string;
  order_number: string;
  quotation_id: string;
  customer_name: string;
  company_name?: string;
  vehicle_name: string;
  brand?: string;
  category?: string;
  quantity: number;
  unit_price: number;
  total_amount: number;
  total_paid: number;
  balance_due: number;
  payment_mode: 'cash' | 'lease';
  payment_structure?: any;
  current_phase: string;
  progress_percentage: number;
  expected_delivery_date?: string;
  actual_delivery_date?: string;
  status: string;
  notes?: string;
  created_at: string;
  updated_at: string;
}

export interface CreateLightVehicleOrderData {
  quotation_id: string;
  payment_mode: 'cash' | 'lease';
  expected_delivery_date?: string;
  notes?: string;
}

export const useLightVehicleOrderManagement = () => {
  const [isLoading, setIsLoading] = useState(false);
  const { user } = useAuth();

  // Get confirmed quotations that haven't been converted to orders
  const getConfirmedQuotations = async () => {
    try {
      const { data, error } = await supabase
        .from('lightvehicle_quotations')
        .select('*')
        .eq('status', 'confirmed')
        .order('created_at', { ascending: false });

      if (error) throw error;

      // Filter out quotations that already have orders
      const { data: existingOrders } = await supabase
        .from('lightvehicle_orders')
        .select('quotation_id');

      const convertedQuotationIds = new Set(
        existingOrders?.map(o => o.quotation_id).filter(Boolean) || []
      );

      const availableQuotations = data?.filter(
        q => !convertedQuotationIds.has(q.id)
      ) || [];

      return { success: true, quotations: availableQuotations };
    } catch (error) {
      console.error('Error fetching confirmed quotations:', error);
      return { success: false, error, quotations: [] };
    }
  };

  // Convert quotation to order
  const createOrderFromQuotation = async (data: CreateLightVehicleOrderData) => {
    try {
      setIsLoading(true);

      // Get quotation details first
      const { data: quotation, error: quotationError } = await supabase
        .from('lightvehicle_quotations')
        .select('*')
        .eq('id', data.quotation_id)
        .single();

      if (quotationError) throw quotationError;

      // Define payment structure based on mode
      const paymentStructure = data.payment_mode === 'cash' 
        ? { advance: 10, interim: 40, balance: 50 }
        : { advance: 20, balance: 80 }; // Lease mode

      const totalAmount = quotation.grand_total || quotation.total_price || (quotation.unit_price * quotation.quantity);

      // Create order (order_number will be auto-generated by trigger)
      const orderInsert: any = {
        quotation_id: data.quotation_id,
        customer_name: quotation.customer_name,
        company_name: quotation.company_name,
        vehicle_name: quotation.vehicle_name,
        brand: quotation.brand,
        category: quotation.category,
        quantity: quotation.quantity,
        unit_price: quotation.unit_price,
        total_amount: totalAmount,
        total_paid: 0,
        balance_due: totalAmount,
        payment_mode: data.payment_mode,
        payment_structure: paymentStructure,
        expected_delivery_date: data.expected_delivery_date,
        notes: data.notes,
        status: 'pending',
        current_phase: 'order_placed',
        progress_percentage: 10,
        created_by: user?.id,
      };
      
      const { data: order, error: orderError } = await supabase
        .from('lightvehicle_orders')
        .insert(orderInsert)
        .select()
        .single();

      if (orderError) throw orderError;

      // Create payment schedule
      await createPaymentSchedule(order.id, totalAmount, data.payment_mode, paymentStructure);

      // Update quotation status to converted
      await supabase
        .from('lightvehicle_quotations')
        .update({ status: 'converted_to_order' })
        .eq('id', data.quotation_id);

      toast.success('Order created successfully from quotation');
      return { success: true, order };
    } catch (error: any) {
      console.error('Error creating order:', error);
      toast.error(error.message || 'Failed to create order from quotation');
      return { success: false, error };
    } finally {
      setIsLoading(false);
    }
  };

  // Create payment schedule for an order
  const createPaymentSchedule = async (
    orderId: string, 
    totalAmount: number, 
    paymentMode: 'cash' | 'lease',
    paymentStructure: any
  ) => {
    const schedules = [];
    const baseDate = new Date();

    if (paymentMode === 'cash') {
      // Cash payment: 10% advance, 40% interim, 50% balance
      schedules.push({
        order_id: orderId,
        milestone_name: 'Order Confirmation Advance',
        payment_type: 'advance',
        amount: (totalAmount * paymentStructure.advance) / 100,
        due_date: new Date().toISOString().split('T')[0],
        sequence_order: 1
      });

      schedules.push({
        order_id: orderId,
        milestone_name: 'Interim Payment',
        payment_type: 'interim',
        amount: (totalAmount * paymentStructure.interim) / 100,
        due_date: new Date(baseDate.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        sequence_order: 2
      });

      schedules.push({
        order_id: orderId,
        milestone_name: 'Balance Payment on Delivery',
        payment_type: 'balance',
        amount: (totalAmount * paymentStructure.balance) / 100,
        due_date: new Date(baseDate.getTime() + 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        sequence_order: 3
      });
    } else {
      // Lease payment: 20% advance, 80% through bank
      schedules.push({
        order_id: orderId,
        milestone_name: 'Lease Down Payment',
        payment_type: 'advance',
        amount: (totalAmount * paymentStructure.advance) / 100,
        due_date: new Date().toISOString().split('T')[0],
        sequence_order: 1
      });

      schedules.push({
        order_id: orderId,
        milestone_name: 'Bank Lease Financing',
        payment_type: 'balance',
        amount: (totalAmount * paymentStructure.balance) / 100,
        due_date: new Date(baseDate.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        sequence_order: 2
      });
    }

    const { error } = await supabase
      .from('lightvehicle_payment_schedules')
      .insert(schedules);

    if (error) throw error;
  };

  // Get orders with related data
  const getOrdersWithDetails = async () => {
    try {
      const { data, error } = await supabase
        .from('lightvehicle_orders')
        .select(`
          *,
          lightvehicle_quotations (
            quotation_number,
            customer_name,
            customer_phone,
            customer_email,
            company_name,
            customer_address
          )
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return { success: true, orders: data };
    } catch (error) {
      console.error('Error fetching orders:', error);
      return { success: false, error, orders: [] };
    }
  };

  // Update order phase
  const updateOrderPhase = async (orderId: string, newPhase: string, progressPercentage?: number) => {
    try {
      setIsLoading(true);

      const updates: any = {
        current_phase: newPhase,
        updated_at: new Date().toISOString()
      };

      if (progressPercentage !== undefined) {
        updates.progress_percentage = progressPercentage;
      }

      const { error } = await supabase
        .from('lightvehicle_orders')
        .update(updates)
        .eq('id', orderId);

      if (error) throw error;

      toast.success('Order phase updated successfully');
      return { success: true };
    } catch (error) {
      console.error('Error updating order phase:', error);
      toast.error('Failed to update order phase');
      return { success: false, error };
    } finally {
      setIsLoading(false);
    }
  };

  // Get payment schedules for an order
  const getPaymentSchedules = async (orderId: string) => {
    try {
      const { data, error } = await supabase
        .from('lightvehicle_payment_schedules')
        .select(`
          *,
          lightvehicle_customer_payments (*)
        `)
        .eq('order_id', orderId)
        .order('sequence_order', { ascending: true });

      if (error) throw error;
      return { success: true, schedules: data };
    } catch (error) {
      console.error('Error fetching payment schedules:', error);
      return { success: false, error, schedules: [] };
    }
  };

  // Record customer payment
  const recordCustomerPayment = async (paymentData: {
    order_id: string;
    payment_schedule_id?: string;
    payment_amount: number;
    payment_date: string;
    payment_method: string;
    payment_reference?: string;
    notes?: string;
  }) => {
    try {
      setIsLoading(true);

      const paymentInsert: any = {
        order_id: paymentData.order_id,
        payment_schedule_id: paymentData.payment_schedule_id,
        amount: paymentData.payment_amount,
        payment_date: paymentData.payment_date,
        payment_method: paymentData.payment_method,
        reference_number: paymentData.payment_reference,
        notes: paymentData.notes,
        created_by: user?.id,
      };

      const { error } = await supabase
        .from('lightvehicle_customer_payments')
        .insert(paymentInsert);

      if (error) throw error;

      // Update payment schedule status if linked
      if (paymentData.payment_schedule_id) {
        await supabase
          .from('lightvehicle_payment_schedules')
          .update({ 
            status: 'paid',
            payment_date: paymentData.payment_date,
            payment_reference: paymentData.payment_reference 
          })
          .eq('id', paymentData.payment_schedule_id);
      }

      // ==========================================
      // FINANCE INTEGRATION: POST PAYMENT TO GL
      // ==========================================
      try {
          const { data: orderDetails } = await supabase
              .from('lightvehicle_orders')
              .select(`*, lightvehicle_quotations(customer_name)`)
              .eq('id', paymentData.order_id)
              .single();

          if (orderDetails) {
              const settings = await fetchVehicleFinanceSettings('lightvehicle', NCG_HOLDING_ID);
              
              if (settings) {
                  const description = `ADVANCE PAYMENT FOR LIGHT VEHICLE ORDER ${orderDetails.order_number} - ${orderDetails.lightvehicle_quotations?.customer_name || 'CUSTOMER'}`;
                  
                  await postVehiclePaymentToGL({
                      module: 'lightvehicle',
                      orderNo: orderDetails.order_number,
                      customerName: orderDetails.lightvehicle_quotations?.customer_name || 'CUSTOMER',
                      amount: paymentData.payment_amount,
                      paymentType: 'advance',
                      paymentMethod: paymentData.payment_method,
                      settings,
                      effectiveCompanyId: NCG_HOLDING_ID,
                      paymentDate: paymentData.payment_date,
                  });
              }
          }
      } catch (glError) {
          console.error('Error posting Light Vehicle payment to GL:', glError);
          toast.error('Payment recorded but GL posting failed.');
      }

      toast.success('Customer payment recorded successfully');
      return { success: true };
    } catch (error) {
      console.error('Error recording payment:', error);
      toast.error('Failed to record customer payment');
      return { success: false, error };
    } finally {
      setIsLoading(false);
    }
  };

  return {
    isLoading,
    getConfirmedQuotations,
    createOrderFromQuotation,
    getOrdersWithDetails,
    updateOrderPhase,
    getPaymentSchedules,
    recordCustomerPayment,
  };
};
