import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { toast } from 'sonner';

export interface SinotrukOrder {
    id: string;
    order_no: string;
    quotation_id: string;
    customer_id?: string;
    truck_model: string;
    quantity: number;
    unit_price: number;
    total_amount: number;
    payment_mode: 'cash' | 'lease';
    payment_structure?: any;
    current_phase: string;
    order_date: string;
    expected_delivery_date?: string;
    actual_delivery_date?: string;
    status: string;
    progress_percentage: number;
    notes?: string;
    total_paid: number;
    balance_due: number;
    created_at: string;
    updated_at: string;
}

export interface CreateOrderData {
    quotation_id: string;
    customer_id?: string;
    payment_mode: 'cash' | 'lease';
    expected_delivery_date?: string;
    notes?: string;
}

export const useSinotrukOrderManagement = () => {
    const [isLoading, setIsLoading] = useState(false);
    const { user } = useAuth();

    // Convert quotation to order
    const createOrderFromQuotation = async (data: CreateOrderData) => {
        try {
            setIsLoading(true);

            // Get quotation details first
            const { data: quotation, error: quotationError } = await supabase
                .from('sinotruck_quotations')
                .select('*')
                .eq('id', data.quotation_id)
                .single();

            if (quotationError) throw quotationError;

            // Define payment structure based on mode
            const paymentStructure = data.payment_mode === 'cash'
                ? { advance: 50, balance: 50 } // Based on Sinotruk default terms
                : { advance: 20, balance: 80 }; // Standard lease terms

            // Create order (order_no will be auto-generated by trigger)
            const { data: order, error: orderError } = await (supabase as any)
                .from('sinotruck_orders')
                .insert({
                    quotation_id: data.quotation_id,
                    customer_id: data.customer_id,
                    truck_model: quotation.truck_model_name, // Note: using truck_model_name from quotation
                    quantity: quotation.quantity,
                    unit_price: quotation.unit_price,
                    total_amount: quotation.total_price,
                    payment_mode: data.payment_mode,
                    payment_structure: paymentStructure,
                    expected_delivery_date: data.expected_delivery_date,
                    notes: data.notes,
                    balance_due: quotation.total_price,
                    created_by: user?.id,
                } as any)
                .select()
                .single();

            if (orderError) throw orderError;

            // Create payment schedule
            await createPaymentSchedule(order.id, quotation.total_price, data.payment_mode, paymentStructure);

            // Update quotation status to converted
            await supabase
                .from('sinotruck_quotations')
                .update({ status: 'converted_to_order' })
                .eq('id', data.quotation_id);

            toast.success('Order created successfully from quotation');
            return { success: true, order };
        } catch (error) {
            console.error('Error creating order:', error);
            toast.error('Failed to create order from quotation');
            return { success: false, error };
        } finally {
            setIsLoading(false);
        }
    };

    // Create payment schedule for an order
    const createPaymentSchedule = async (
        orderId: string,
        totalAmount: number,
        paymentMode: 'cash' | 'lease',
        paymentStructure: any
    ) => {
        const schedules = [];
        const baseDate = new Date();

        if (paymentMode === 'cash') {
            // Cash payment: 50% advance, 50% balance
            schedules.push({
                order_id: orderId,
                milestone_name: 'Order Confirmation Advance',
                payment_type: 'advance',
                amount: (totalAmount * paymentStructure.advance) / 100,
                due_date: new Date().toISOString().split('T')[0],
                sequence_order: 1
            });

            schedules.push({
                order_id: orderId,
                milestone_name: 'Balance Payment',
                payment_type: 'balance',
                amount: (totalAmount * paymentStructure.balance) / 100,
                due_date: new Date(baseDate.getTime() + 60 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 60 days delivery
                sequence_order: 2
            });
        } else {
            // Lease payment: 20% advance, 80% through bank
            schedules.push({
                order_id: orderId,
                milestone_name: 'Lease Down Payment',
                payment_type: 'advance',
                amount: (totalAmount * paymentStructure.advance) / 100,
                due_date: new Date().toISOString().split('T')[0],
                sequence_order: 1
            });

            schedules.push({
                order_id: orderId,
                milestone_name: 'Bank Lease Financing',
                payment_type: 'balance',
                amount: (totalAmount * paymentStructure.balance) / 100,
                due_date: new Date(baseDate.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
                sequence_order: 2,
                is_lc_payment: true
            });
        }

        const { error } = await (supabase as any)
            .from('sinotruck_payment_schedules')
            .insert(schedules);

        if (error) throw error;
    };

    // Get orders with related data
    const getOrdersWithDetails = async () => {
        try {
            const { data, error } = await (supabase as any)
                .from('sinotruck_orders')
                .select(`
          *,
          sinotruck_quotations (
            quotation_no,
            customer_name,
            contact_number,
            customer_address
          )
        `)
                .order('created_at', { ascending: false });

            if (error) throw error;
            return { success: true, orders: data };
        } catch (error) {
            console.error('Error fetching orders:', error);
            return { success: false, error };
        }
    };

    // Update order phase
    const updateOrderPhase = async (orderId: string, newPhase: string, progressPercentage?: number) => {
        try {
            setIsLoading(true);

            const updates: any = {
                current_phase: newPhase,
                updated_at: new Date().toISOString()
            };

            if (progressPercentage !== undefined) {
                updates.progress_percentage = progressPercentage;
            }

            const { error } = await (supabase as any)
                .from('sinotruck_orders')
                .update(updates)
                .eq('id', orderId);

            if (error) throw error;

            toast.success('Order phase updated successfully');
            return { success: true };
        } catch (error) {
            console.error('Error updating order phase:', error);
            toast.error('Failed to update order phase');
            return { success: false, error };
        } finally {
            setIsLoading(false);
        }
    };

    // Get payment schedules for an order
    const getPaymentSchedules = async (orderId: string) => {
        try {
            const { data, error } = await (supabase as any)
                .from('sinotruck_payment_schedules')
                .select(`
          *,
          sinotruck_customer_payments (*)
        `)
                .eq('order_id', orderId)
                .order('sequence_order', { ascending: true });

            if (error) throw error;
            return { success: true, schedules: data };
        } catch (error) {
            console.error('Error fetching payment schedules:', error);
            return { success: false, error };
        }
    };

    // Record customer payment
    const recordCustomerPayment = async (paymentData: {
        order_id: string;
        payment_schedule_id?: string;
        payment_amount: number;
        payment_date: string;
        payment_method: string;
        payment_reference?: string;
        bank_name?: string;
        cheque_no?: string;
        bank_slip_no?: string;
        notes?: string;
    }) => {
        try {
            setIsLoading(true);

            const { error } = await (supabase as any)
                .from('sinotruck_customer_payments')
                .insert({
                    ...paymentData,
                    created_by: user?.id,
                    status: 'pending'
                });

            if (error) throw error;

            // Update payment schedule status if linked
            if (paymentData.payment_schedule_id) {
                await (supabase as any)
                    .from('sinotruck_payment_schedules')
                    .update({
                        status: 'paid',
                        payment_date: paymentData.payment_date,
                        payment_reference: paymentData.payment_reference
                    })
                    .eq('id', paymentData.payment_schedule_id);
            }

            toast.success('Customer payment recorded successfully');
            return { success: true };
        } catch (error) {
            console.error('Error recording payment:', error);
            toast.error('Failed to record customer payment');
            return { success: false, error };
        } finally {
            setIsLoading(false);
        }
    };

    // Verify payment and trigger GL posting
    const verifyPayment = async (paymentId: string) => {
        try {
            setIsLoading(true);

            const { error } = await (supabase as any)
                .from('sinotruck_customer_payments')
                .update({
                    status: 'verified',
                    verified_at: new Date().toISOString(),
                    verified_by: user?.id
                })
                .eq('id', paymentId);

            if (error) throw error;

            toast.success('Payment verified. GL posting triggered via payment tracking.');
            return { success: true };
        } catch (error) {
            console.error('Error verifying payment:', error);
            toast.error('Failed to verify payment');
            return { success: false, error };
        } finally {
            setIsLoading(false);
        }
    };

    // Update order financials after payment verification
    const updateOrderFinancials = async (orderId: string) => {
        try {
            // Get all verified payments for the order
            const { data: verifiedPayments, error: paymentsError } = await (supabase as any)
                .from('sinotruck_customer_payments')
                .select('payment_amount')
                .eq('order_id', orderId)
                .eq('status', 'verified');

            if (paymentsError) throw paymentsError;

            const totalPaid = verifiedPayments?.reduce((sum: number, p: any) => sum + p.payment_amount, 0) || 0;

            // Get order to calculate balance
            const { data: order, error: orderError } = await (supabase as any)
                .from('sinotruck_orders')
                .select('total_amount')
                .eq('id', orderId)
                .single();

            if (orderError) throw orderError;

            const balanceDue = (order?.total_amount || 0) - totalPaid;

            // Update order
            await (supabase as any)
                .from('sinotruck_orders')
                .update({
                    total_paid: totalPaid,
                    balance_due: balanceDue
                })
                .eq('id', orderId);

            return { success: true, totalPaid, balanceDue };
        } catch (error) {
            console.error('Error updating order financials:', error);
            return { success: false, error };
        }
    };

    return {
        isLoading,
        createOrderFromQuotation,
        getOrdersWithDetails,
        updateOrderPhase,
        getPaymentSchedules,
        recordCustomerPayment,
        verifyPayment,
        updateOrderFinancials,
    };
};
