import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { toast } from 'sonner';

export interface YutongOrder {
  id: string;
  order_no: string;
  quotation_id: string;
  customer_id?: string;
  bus_model: string;
  quantity: number;
  unit_price: number;
  total_amount: number;
  engine_type?: string;
  gearbox_type?: string;
  seating_capacity?: number;
  color_scheme?: string;
  special_features?: any;
  payment_mode: 'cash' | 'lease';
  payment_structure?: any;
  current_phase: string;
  order_date: string;
  expected_delivery_date?: string;
  actual_delivery_date?: string;
  status: string;
  progress_percentage: number;
  notes?: string;
  total_paid: number;
  balance_due: number;
  created_at: string;
  updated_at: string;
}

export interface CreateOrderData {
  quotation_id: string;
  customer_id?: string;
  engine_type?: string;
  gearbox_type?: string;
  seating_capacity?: number;
  color_scheme?: string;
  special_features?: string[];
  payment_mode: 'cash' | 'lease';
  expected_delivery_date?: string;
  notes?: string;
}

export const useYutongOrderManagement = () => {
  const [isLoading, setIsLoading] = useState(false);
  const { user } = useAuth();

  // Convert quotation to order
  const createOrderFromQuotation = async (data: CreateOrderData) => {
    try {
      setIsLoading(true);

      // Get quotation details first
      const { data: quotation, error: quotationError } = await supabase
        .from('yutong_quotations')
        .select('*')
        .eq('id', data.quotation_id)
        .single();

      if (quotationError) throw quotationError;

      // Define payment structure based on mode
      const paymentStructure = data.payment_mode === 'cash' 
        ? { advance: 10, interim: 40, balance: 50 }
        : { advance: 20, balance: 80 }; // Lease mode

      // Create order (order_no will be auto-generated by trigger)
      const { data: order, error: orderError } = await supabase
        .from('yutong_orders')
        .insert({
          quotation_id: data.quotation_id,
          customer_id: data.customer_id,
          bus_model: quotation.bus_model,
          quantity: quotation.quantity,
          unit_price: quotation.unit_price,
          total_amount: quotation.total_price,
          engine_type: data.engine_type,
          gearbox_type: data.gearbox_type,
          seating_capacity: data.seating_capacity,
          color_scheme: data.color_scheme,
          special_features: data.special_features || [],
          payment_mode: data.payment_mode,
          payment_structure: paymentStructure,
          expected_delivery_date: data.expected_delivery_date,
          notes: data.notes,
          balance_due: quotation.total_price,
          created_by: user?.id,
        } as any)
        .select()
        .single();

      if (orderError) throw orderError;

      // Create payment schedule
      await createPaymentSchedule(order.id, quotation.total_price, data.payment_mode, paymentStructure);

      // Update quotation status to converted
      await supabase
        .from('yutong_quotations')
        .update({ status: 'converted_to_order' })
        .eq('id', data.quotation_id);

      toast.success('Order created successfully from quotation');
      return { success: true, order };
    } catch (error) {
      console.error('Error creating order:', error);
      toast.error('Failed to create order from quotation');
      return { success: false, error };
    } finally {
      setIsLoading(false);
    }
  };

  // Create payment schedule for an order
  const createPaymentSchedule = async (
    orderId: string, 
    totalAmount: number, 
    paymentMode: 'cash' | 'lease',
    paymentStructure: any
  ) => {
    const schedules = [];
    const baseDate = new Date();

    if (paymentMode === 'cash') {
      // Cash payment: 10% advance, 40% interim, 50% balance
      schedules.push({
        order_id: orderId,
        milestone_name: 'Order Confirmation Advance',
        payment_type: 'advance',
        amount: (totalAmount * paymentStructure.advance) / 100,
        due_date: new Date().toISOString().split('T')[0],
        sequence_order: 1
      });

      schedules.push({
        order_id: orderId,
        milestone_name: 'LC Issuance Payment',
        payment_type: 'interim',
        amount: (totalAmount * paymentStructure.interim) / 100,
        due_date: new Date(baseDate.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        sequence_order: 2,
        is_lc_payment: true
      });

      schedules.push({
        order_id: orderId,
        milestone_name: 'Balance Payment',
        payment_type: 'balance',
        amount: (totalAmount * paymentStructure.balance) / 100,
        due_date: new Date(baseDate.getTime() + 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        sequence_order: 3
      });
    } else {
      // Lease payment: 20% advance, 80% through bank
      schedules.push({
        order_id: orderId,
        milestone_name: 'Lease Down Payment',
        payment_type: 'advance',
        amount: (totalAmount * paymentStructure.advance) / 100,
        due_date: new Date().toISOString().split('T')[0],
        sequence_order: 1
      });

      schedules.push({
        order_id: orderId,
        milestone_name: 'Bank Lease Financing',
        payment_type: 'balance',
        amount: (totalAmount * paymentStructure.balance) / 100,
        due_date: new Date(baseDate.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        sequence_order: 2,
        is_lc_payment: true
      });
    }

    const { error } = await supabase
      .from('yutong_payment_schedules')
      .insert(schedules);

    if (error) throw error;
  };

  // Get orders with related data
  const getOrdersWithDetails = async () => {
    try {
      const { data, error } = await supabase
        .from('yutong_orders')
        .select(`
          *,
          yutong_quotations (
            quotation_no,
            customer_name,
            customer_phone,
            customer_email,
            company_name
          )
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return { success: true, orders: data };
    } catch (error) {
      console.error('Error fetching orders:', error);
      return { success: false, error };
    }
  };

  // Update order phase
  const updateOrderPhase = async (orderId: string, newPhase: string, progressPercentage?: number) => {
    try {
      setIsLoading(true);

      const updates: any = {
        current_phase: newPhase,
        updated_at: new Date().toISOString()
      };

      if (progressPercentage !== undefined) {
        updates.progress_percentage = progressPercentage;
      }

      const { error } = await supabase
        .from('yutong_orders')
        .update(updates)
        .eq('id', orderId);

      if (error) throw error;

      toast.success('Order phase updated successfully');
      return { success: true };
    } catch (error) {
      console.error('Error updating order phase:', error);
      toast.error('Failed to update order phase');
      return { success: false, error };
    } finally {
      setIsLoading(false);
    }
  };

  // Get payment schedules for an order
  const getPaymentSchedules = async (orderId: string) => {
    try {
      const { data, error } = await supabase
        .from('yutong_payment_schedules')
        .select(`
          *,
          yutong_customer_payments (*)
        `)
        .eq('order_id', orderId)
        .order('sequence_order', { ascending: true });

      if (error) throw error;
      return { success: true, schedules: data };
    } catch (error) {
      console.error('Error fetching payment schedules:', error);
      return { success: false, error };
    }
  };

  // Record customer payment
  const recordCustomerPayment = async (paymentData: {
    order_id: string;
    payment_schedule_id?: string;
    payment_amount: number;
    payment_date: string;
    payment_method: string;
    payment_reference?: string;
    bank_name?: string;
    cheque_no?: string;
    bank_slip_no?: string;
    notes?: string;
  }) => {
    try {
      setIsLoading(true);

      const { error } = await supabase
        .from('yutong_customer_payments')
        .insert({
          ...paymentData,
          created_by: user?.id,
          status: 'received'
        });

      if (error) throw error;

      // Update payment schedule status if linked
      if (paymentData.payment_schedule_id) {
        await supabase
          .from('yutong_payment_schedules')
          .update({ 
            status: 'paid',
            payment_date: paymentData.payment_date,
            payment_reference: paymentData.payment_reference 
          })
          .eq('id', paymentData.payment_schedule_id);
      }

      toast.success('Customer payment recorded successfully');
      return { success: true };
    } catch (error) {
      console.error('Error recording payment:', error);
      toast.error('Failed to record customer payment');
      return { success: false, error };
    } finally {
      setIsLoading(false);
    }
  };

  return {
    isLoading,
    createOrderFromQuotation,
    getOrdersWithDetails,
    updateOrderPhase,
    getPaymentSchedules,
    recordCustomerPayment,
  };
};