import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { Upload, Check, Loader2 } from 'lucide-react';
import { createAnonymousClient } from '@/integrations/supabase/public-client';

export default function PublicConductorUpload() {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [submissionCode, setSubmissionCode] = useState('');
  const [formData, setFormData] = useState({
    conductorName: '',
    conductorPhone: '',
    busNumber: '',
    image: null as File | null
  });

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      if (file.size > 10 * 1024 * 1024) {
        toast({
          title: "File Too Large",
          description: "Please select an image under 10MB",
          variant: "destructive"
        });
        return;
      }
      setFormData({ ...formData, image: file });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.conductorName || !formData.conductorPhone || !formData.image) {
      toast({
        title: "Missing Information",
        description: "Please fill in all required fields",
        variant: "destructive"
      });
      return;
    }

    setLoading(true);

    try {
      const supabasePublic = createAnonymousClient();
      
      // Upload image to storage
      const fileExt = formData.image.name.split('.').pop();
      const fileName = `${Date.now()}-${Math.random().toString(36).substring(7)}.${fileExt}`;
      const filePath = `conductor-submissions/${fileName}`;

      const { error: uploadError } = await supabasePublic.storage
        .from('documents')
        .upload(filePath, formData.image);

      if (uploadError) throw uploadError;

      // Get public URL
      const { data: { publicUrl } } = supabasePublic.storage
        .from('documents')
        .getPublicUrl(filePath);

      // Create submission record (submission_code will be auto-generated by trigger)
      const { data, error: insertError } = await supabasePublic
        .from('conductor_submissions')
        .insert({
          conductor_name: formData.conductorName,
          conductor_phone: formData.conductorPhone,
          bus_number: formData.busNumber || null,
          image_url: publicUrl,
          status: 'pending',
          submission_code: '' // Will be replaced by trigger
        })
        .select('submission_code')
        .single();

      if (insertError) throw insertError;

      setSubmissionCode(data.submission_code);
      setSubmitted(true);

      toast({
        title: "Submission Successful!",
        description: "Your trip sheet has been submitted for review."
      });

    } catch (error: any) {
      console.error('Submission error:', error);
      toast({
        title: "Submission Failed",
        description: error.message || "Please try again",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  if (submitted) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-background to-secondary/20 flex items-center justify-center p-4">
        <Card className="w-full max-w-md">
          <CardHeader className="text-center">
            <div className="mx-auto w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mb-4">
              <Check className="h-6 w-6 text-primary" />
            </div>
            <CardTitle className="text-2xl">Submission Received!</CardTitle>
            <CardDescription>
              Your trip sheet has been successfully submitted
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="rounded-lg border bg-primary/5 p-4 text-center">
              <p className="text-sm text-muted-foreground mb-2">Your tracking code:</p>
              <p className="text-2xl font-bold font-mono text-primary">{submissionCode}</p>
              <p className="text-xs text-muted-foreground mt-2">
                Save this code for tracking your submission
              </p>
            </div>

            <div className="space-y-2 text-sm text-muted-foreground">
              <p>✓ Your image has been uploaded</p>
              <p>✓ Our team will review it shortly</p>
              <p>✓ Data will be processed and verified</p>
            </div>

            <Button
              onClick={() => {
                setSubmitted(false);
                setFormData({
                  conductorName: '',
                  conductorPhone: '',
                  busNumber: '',
                  image: null
                });
              }}
              className="w-full"
              variant="outline"
            >
              Submit Another Trip Sheet
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-secondary/20 flex items-center justify-center p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl">Upload Trip Sheet</CardTitle>
          <CardDescription>
            Submit your daily trip sheet for processing
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="conductorName">Your Name *</Label>
              <Input
                id="conductorName"
                value={formData.conductorName}
                onChange={(e) => setFormData({ ...formData, conductorName: e.target.value })}
                placeholder="Enter your full name"
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="conductorPhone">Phone Number *</Label>
              <Input
                id="conductorPhone"
                value={formData.conductorPhone}
                onChange={(e) => setFormData({ ...formData, conductorPhone: e.target.value })}
                placeholder="07XXXXXXXX"
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="busNumber">Bus Number (Optional)</Label>
              <Input
                id="busNumber"
                value={formData.busNumber}
                onChange={(e) => setFormData({ ...formData, busNumber: e.target.value })}
                placeholder="e.g., NA-1234"
              />
              <p className="text-xs text-muted-foreground">
                Will be extracted from image if not provided
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="image">Trip Sheet Image *</Label>
              <Input
                id="image"
                type="file"
                accept="image/*"
                onChange={handleImageChange}
                required
              />
              <p className="text-xs text-muted-foreground">
                Upload a clear photo of your trip sheet (Max 10MB)
              </p>
            </div>

            <Button type="submit" disabled={loading} className="w-full">
              {loading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Uploading...
                </>
              ) : (
                <>
                  <Upload className="mr-2 h-4 w-4" />
                  Submit Trip Sheet
                </>
              )}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}