-- Import Management Reports with correct weekday format
-- Add missing frequency rules
INSERT INTO frequency_rules (rule_type, params, description) VALUES
  ('MONTHLY_BY_DAY', '{"day": 10}', '10th of each month'),
  ('MONTHLY_BY_DAY', '{"day": 25}', '25th of each month')
ON CONFLICT DO NOTHING;

-- NAS Reports
INSERT INTO governance_items (title, type, category, company_id, frequency_rule_id, owner_name, owner_email, notes, is_active) VALUES
('Monthly Financial Statement (Performance Basis)', 'REPORT', 'Financial Reporting', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'Finance Manager', 'finance@nas.lk', 'Submission due by 8th', true),
('Cashflow Statement (Budgeted Vs Actuals)', 'REPORT', 'Financial Reporting', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'Finance Manager', 'finance@nas.lk', 'Submission due by 8th', true),
('Department wise Revenue, Cost and GP', 'REPORT', 'Operational Analytics', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'WEEKLY_BY_WEEKDAY' AND params->>'weekday' = 'MON' LIMIT 1), 'Finance Manager', 'finance@nas.lk', 'Weekly - Excluding salaries', true),
('Location wise - PnL', 'REPORT', 'Operational Analytics', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'WEEKLY_BY_WEEKDAY' AND params->>'weekday' = 'MON' LIMIT 1), 'Finance Manager', 'finance@nas.lk', 'HR provides labour cost', true),
('Internal & External Collection', 'REPORT', 'Collections & Receivables', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'WEEKLY_BY_WEEKDAY' AND params->>'weekday' = 'MON' LIMIT 1), 'Finance Manager', 'finance@nas.lk', 'Weekly Monday', true),
('Accounts Receivables Ageing', 'REPORT', 'Collections & Receivables', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'WEEKLY_BY_WEEKDAY' AND params->>'weekday' = 'MON' LIMIT 1), 'Finance Manager', 'finance@nas.lk', 'Weekly Monday', true),
('Internal NAS Ops Vehicle Fuel Usage', 'REPORT', 'Fuel & Maintenance', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'Operations Manager', 'ops@nas.lk', 'Including break-down. Submit on 8th', true),
('Supplier Ageing', 'REPORT', 'Collections & Receivables', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'WEEKLY_BY_WEEKDAY' AND params->>'weekday' = 'MON' LIMIT 1), 'Finance Manager', 'finance@nas.lk', 'Weekly Monday', true),
('Labour Cost Vs Labour Revenue', 'REPORT', 'Operational Analytics', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'HR Manager', 'hr@nas.lk', 'Submit on 8th', true),
('Parts Cost Vs Parts Revenue', 'REPORT', 'Inventory & Parts', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTH_END' LIMIT 1), 'Operations Manager', 'ops@nas.lk', 'Monthly', true),
('Inventory Item Value Report', 'REPORT', 'Inventory & Parts', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTH_END' LIMIT 1), 'Operations Manager', 'ops@nas.lk', 'Monthly', true),
('Other Analytics - Revenue/Expense', 'REPORT', 'Ad-hoc Analytics', (SELECT id FROM companies WHERE name = 'NAS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTH_END' LIMIT 1), 'Finance Manager', 'finance@nas.lk', 'Month on Month', true);

-- NSP Reports  
INSERT INTO governance_items (title, type, category, company_id, frequency_rule_id, owner_name, owner_email, notes, is_active) VALUES
('Monthly Financial Statement (Performance Basis)', 'REPORT', 'Financial Reporting', (SELECT id FROM companies WHERE name = 'NSP' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'Finance Manager', 'finance@nsp.lk', 'Submit by 8th', true),
('Cashflow Statement (Budgeted Vs Actuals)', 'REPORT', 'Financial Reporting', (SELECT id FROM companies WHERE name = 'NSP' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'Finance Manager', 'finance@nsp.lk', 'Submit by 8th', true),
('Accounts Receivables Aging', 'REPORT', 'Collections & Receivables', (SELECT id FROM companies WHERE name = 'NSP' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'WEEKLY_BY_WEEKDAY' AND params->>'weekday' = 'MON' LIMIT 1), 'Finance Manager', 'finance@nsp.lk', 'Weekly Monday', true),
('Supplier Ageing', 'REPORT', 'Collections & Receivables', (SELECT id FROM companies WHERE name = 'NSP' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'WEEKLY_BY_WEEKDAY' AND params->>'weekday' = 'MON' LIMIT 1), 'Finance Manager', 'finance@nsp.lk', 'Weekly Monday', true),
('Vendor Aging', 'REPORT', 'Collections & Receivables', (SELECT id FROM companies WHERE name = 'NSP' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'Finance Manager', 'finance@nsp.lk', 'Monthly by 8th', true),
('Daily Bank Balance', 'REPORT', 'Daily Operations', (SELECT id FROM companies WHERE name = 'NSP' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'DAILY' LIMIT 1), 'Finance Manager', 'finance@nsp.lk', 'Daily', true),
('Parts Cost Vs Parts Revenue', 'REPORT', 'Inventory & Parts', (SELECT id FROM companies WHERE name = 'NSP' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '5' LIMIT 1), 'Operations Manager', 'ops@nsp.lk', 'Submit by 5th', true),
('Inventory Item Value Report', 'REPORT', 'Inventory & Parts', (SELECT id FROM companies WHERE name = 'NSP' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '5' LIMIT 1), 'Operations Manager', 'ops@nsp.lk', 'Submit by 5th', true),
('Other Analytics - Revenue/Expense', 'REPORT', 'Ad-hoc Analytics', (SELECT id FROM companies WHERE name = 'NSP' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTH_END' LIMIT 1), 'Finance Manager', 'finance@nsp.lk', 'Month on Month', true);

-- NEX Company-level
INSERT INTO governance_items (title, type, category, company_id, frequency_rule_id, owner_name, owner_email, notes, is_active) VALUES
('Monthly Financial Statement (Performance Basis)', 'REPORT', 'Financial Reporting', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Submit by 8th', true),
('Cashflow Statement (Budgeted Vs Actuals)', 'REPORT', 'Financial Reporting', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Submit by 8th', true);

-- NEX PBS
INSERT INTO governance_items (title, type, category, company_id, sbu_id, frequency_rule_id, owner_name, owner_email, notes, is_active) VALUES
('PBS Route/bus wise Income & Expenses', 'REPORT', 'Daily Operations', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'PBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'DAILY' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Daily', true),
('PBS Profitability report', 'REPORT', 'Operational Analytics', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'PBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '15' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Submit by 15th', true),
('PBS Fuel Consumption report', 'REPORT', 'Fuel & Maintenance', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'PBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTH_END' LIMIT 1), 'Operations Manager', 'ops@nex.lk', 'Dependent on OPS report', true),
('PBS Maintenance & Repair Cost', 'REPORT', 'Fuel & Maintenance', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'PBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'Operations Manager', 'ops@nex.lk', 'Included in 8th Report', true),
('PBS Adhoc reports', 'REPORT', 'Ad-hoc Analytics', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'PBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTH_END' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'As needed', true),
('PBS Cost & Revenue analysis', 'REPORT', 'Operational Analytics', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'PBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTH_END' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Month end', true);

-- NEX SBS
INSERT INTO governance_items (title, type, category, company_id, sbu_id, frequency_rule_id, owner_name, owner_email, notes, is_active) VALUES
('SBS Profitability report', 'REPORT', 'Operational Analytics', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '15' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Submit by 15th', true),
('SBS Weekly O/S report', 'REPORT', 'Collections & Receivables', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'WEEKLY_BY_WEEKDAY' AND params->>'weekday' = 'MON' LIMIT 1), 'Operations Manager', 'ops@nex.lk', 'Dependent on OPS', true),
('SBS Daily Collection', 'REPORT', 'Daily Operations', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'DAILY' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Daily', true),
('SBS Maintenance & Repair Cost', 'REPORT', 'Fuel & Maintenance', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'Operations Manager', 'ops@nex.lk', 'Included in 8th Report', true),
('SBS Fuel Consumption report', 'REPORT', 'Fuel & Maintenance', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTH_END' LIMIT 1), 'Operations Manager', 'ops@nex.lk', 'Dependent on OPS', true),
('SBS Budgeted vs Actual Fuel', 'REPORT', 'Fuel & Maintenance', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'WEEKLY_BY_WEEKDAY' AND params->>'weekday' = 'MON' LIMIT 1), 'Operations Manager', 'ops@nex.lk', 'Dependent on OPS', true),
('SBS Adhoc reports', 'REPORT', 'Ad-hoc Analytics', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTH_END' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'As needed', true),
('SBS Cost & Revenue analysis', 'REPORT', 'Operational Analytics', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SBS' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTH_END' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Month end', true);

-- NEX SH
INSERT INTO governance_items (title, type, category, company_id, sbu_id, frequency_rule_id, owner_name, owner_email, notes, is_active) VALUES
('SH Overall Profitability Report', 'REPORT', 'Operational Analytics', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SH' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '15' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Submit by 15th', true),
('SH Internal & External Revenue', 'REPORT', 'Operational Analytics', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SH' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '15' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Included in 15th', true),
('SH Customer O/S report', 'REPORT', 'Collections & Receivables', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SH' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'WEEKLY_BY_WEEKDAY' AND params->>'weekday' = 'MON' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Weekly Monday', true),
('SH Adhoc reports', 'REPORT', 'Ad-hoc Analytics', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'SH' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTH_END' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'As needed', true);

-- NEX Activity Buses
INSERT INTO governance_items (title, type, category, company_id, sbu_id, frequency_rule_id, owner_name, owner_email, notes, is_active) VALUES
('Activity Buses Monthly income & O/S', 'REPORT', 'Collections & Receivables', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM sbus WHERE name = 'Activity Buses' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '8' LIMIT 1), 'Finance Manager', 'finance@nex.lk', 'Submit by 8th', true);

-- NEX HR Reports
INSERT INTO governance_items (title, type, category, company_id, frequency_rule_id, owner_name, owner_email, notes, is_active) VALUES
('SBS Driver & caretaker salary', 'REPORT', 'HR & Payroll', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '5' LIMIT 1), 'HR Manager', 'hr@nex.lk', 'HR - Submit by 5th', true),
('PBS Driver & conductor salary', 'REPORT', 'HR & Payroll', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '5' LIMIT 1), 'HR Manager', 'hr@nex.lk', 'HR - Submit by 5th', true),
('OT Amounts SBS & PBS', 'REPORT', 'HR & Payroll', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '5' LIMIT 1), 'HR Manager', 'hr@nex.lk', 'HR - Submit by 5th', true),
('Profit sharing report', 'REPORT', 'HR & Payroll', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '10' LIMIT 1), 'HR Manager', 'hr@nex.lk', 'HR - Submit by 10th', true),
('Penalty deduction report', 'REPORT', 'HR & Payroll', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '2' LIMIT 1), 'HR Manager', 'hr@nex.lk', 'HR - Submit by 2nd', true),
('Attendance confirmation', 'REPORT', 'HR & Payroll', (SELECT id FROM companies WHERE name = 'NEX' LIMIT 1), (SELECT id FROM frequency_rules WHERE rule_type = 'MONTHLY_BY_DAY' AND params->>'day' = '25' LIMIT 1), 'HR Manager', 'hr@nex.lk', 'HR - Submit by 25th', true);