
-- 1) Create a sequence for generating employee numbers
CREATE SEQUENCE IF NOT EXISTS public.employee_id_seq;

-- 2) Helper to generate unique employee IDs like EMP-2025-0001
CREATE OR REPLACE FUNCTION public.generate_employee_id()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  seq int;
BEGIN
  seq := nextval('public.employee_id_seq');
  RETURN 'EMP-' || to_char(now(), 'YYYY') || '-' || lpad(seq::text, 4, '0');
END;
$$;

-- 3) BEFORE INSERT trigger function to set employee_id if missing
CREATE OR REPLACE FUNCTION public.set_employee_id()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  IF NEW.employee_id IS NULL OR NEW.employee_id = '' THEN
    NEW.employee_id = public.generate_employee_id();
  END IF;
  RETURN NEW;
END;
$$;

-- 4) Attach the trigger to public.profiles (create only if it doesn't exist)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'profiles_set_employee_id_trg'
  ) THEN
    CREATE TRIGGER profiles_set_employee_id_trg
    BEFORE INSERT ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.set_employee_id();
  END IF;
END $$;

-- 5) Update public.handle_new_user to avoid duplicate employee IDs
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  is_first_user BOOLEAN;
  should_be_admin BOOLEAN DEFAULT FALSE;
  emp_id TEXT;
BEGIN
  -- Check if this is the first user by counting existing profiles
  SELECT COUNT(*) = 0 FROM public.profiles INTO is_first_user;
  
  -- Mark specific email as admin if needed
  IF NEW.email = 'admin@test.com' THEN
    should_be_admin := TRUE;
  END IF;

  -- Only first/explicit admin gets ADMIN001; others are auto-generated by trigger
  IF is_first_user OR should_be_admin THEN
    emp_id := 'ADMIN001';
  ELSE
    emp_id := NULL; -- Allow BEFORE INSERT trigger to generate a unique value
  END IF;
  
  -- Insert profile
  INSERT INTO public.profiles (
    user_id, 
    first_name, 
    last_name, 
    employee_id,
    hire_date,
    status
  ) VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'first_name', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data ->> 'last_name', ''),
    emp_id,
    CURRENT_DATE,
    'active'::user_status
  );
  
  -- Assign role
  IF is_first_user OR should_be_admin THEN
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'admin');
  ELSE
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'staff');
  END IF;
  
  RETURN NEW;
END;
$function$;

-- 6) (Optional safety) Ensure unique constraint exists on employee_id
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'profiles_employee_id_key'
      AND conrelid = 'public.profiles'::regclass
  ) THEN
    ALTER TABLE public.profiles
    ADD CONSTRAINT profiles_employee_id_key UNIQUE (employee_id);
  END IF;
END $$;
