-- Fix Historical GL Postings for Direct Payments
-- 
-- This script repairs incorrect journal entries generated by the GL Guardian for Direct Payments
-- that lacked a bank_account_id at creation. The GL Guardian forced these to "TRADE PAYABLE - INTERNAL".
-- This script remaps the debit line back to the correct account specified in ap_payment_lines.

BEGIN;

-- 1. Identify and update incorrect Journal Entry lines
UPDATE journal_entry_lines
SET 
  account_id = (
    -- Get the correct account from ap_payment_lines
    SELECT apl.account_id
    FROM ap_payments ap
    JOIN ap_payment_lines apl ON apl.payment_id = ap.id
    WHERE ap.journal_entry_id = journal_entry_lines.journal_entry_id
    AND ap.is_direct_payment = true
    LIMIT 1
  ),
  description = COALESCE((
    -- Get the correct description from ap_payment_lines
    SELECT apl.description
    FROM ap_payments ap
    JOIN ap_payment_lines apl ON apl.payment_id = ap.id
    WHERE ap.journal_entry_id = journal_entry_lines.journal_entry_id
    AND ap.is_direct_payment = true
    LIMIT 1
  ), description)
WHERE id IN (
  SELECT jel.id
  FROM journal_entry_lines jel
  JOIN chart_of_accounts coa ON coa.id = jel.account_id
  JOIN ap_payments ap ON ap.journal_entry_id = jel.journal_entry_id
  JOIN ap_payment_lines apl ON apl.payment_id = ap.id
  WHERE ap.is_direct_payment = true
  AND coa.account_name = 'TRADE PAYABLE - INTERNAL'
  AND jel.debit > 0
);

COMMIT;

-- Note: The GL Scanner will no longer double-post new transactions because of the 
-- strict validations we added to useAccountingMutations.ts and usePettyCash.ts.
