import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";

interface ManualInquiryFormProps {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

export const ManualInquiryForm = ({
  open,
  onClose,
  onSuccess,
}: ManualInquiryFormProps) => {
  const { toast } = useToast();
  const [formData, setFormData] = useState({
    source: "phone",
    product_type: "yutong",
    customer_name: "",
    customer_phone: "",
    customer_email: "",
    company_name: "",
    address: "",
    inquiry_message: "",
    interested_model: "",
    quantity: 1,
    budget_range: "",
    priority: "medium",
  });

  // Fetch available models based on product type
  const { data: models } = useQuery({
    queryKey: ["vehicle-models", formData.product_type],
    queryFn: async () => {
      if (formData.product_type === "yutong") {
        const { data } = await supabase
          .from("yutong_bus_models")
          .select("id, model_name")
          .eq("is_active", true);
        return data || [];
      } else if (formData.product_type === "sinotruk") {
        const { data } = await supabase
          .from("sinotruck_truck_models")
          .select("id, model_name")
          .eq("is_active", true);
        return data || [];
      } else if (["honda", "toyota", "mitsubishi", "suzuki"].includes(formData.product_type)) {
        // Light vehicle brands - fetch from lightvehicle_models
        const { data } = await supabase
          .from("lightvehicle_models")
          .select("id, model_name")
          .eq("brand", formData.product_type)
          .eq("is_active", true);
        return data || [];
      }
      return [];
    },
    enabled: open && !!formData.product_type && !["general"].includes(formData.product_type),
  });

  const createInquiryMutation = useMutation({
    mutationFn: async () => {
      const { error } = await supabase.from("vehicle_inquiries").insert([{
        inquiry_number: '', // Will be auto-generated by trigger
        source: formData.source,
        product_type: formData.product_type,
        customer_name: formData.customer_name,
        customer_phone: formData.customer_phone || null,
        customer_email: formData.customer_email || null,
        company_name: formData.company_name || null,
        address: formData.address || null,
        inquiry_message: formData.inquiry_message || null,
        interested_model: formData.interested_model || null,
        quantity: Number(formData.quantity),
        budget_range: formData.budget_range || null,
        priority: formData.priority,
      }] as any);

      if (error) throw error;
    },
    onSuccess: () => {
      toast({ title: "Inquiry created successfully" });
      onSuccess();
      setFormData({
        source: "phone",
        product_type: "yutong",
        customer_name: "",
        customer_phone: "",
        customer_email: "",
        company_name: "",
        address: "",
        inquiry_message: "",
        interested_model: "",
        quantity: 1,
        budget_range: "",
        priority: "medium",
      });
    },
    onError: (error) => {
      toast({
        title: "Error creating inquiry",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.customer_name || !formData.product_type) {
      toast({
        title: "Missing required fields",
        description: "Please fill in customer name and product type",
        variant: "destructive",
      });
      return;
    }
    createInquiryMutation.mutate();
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Add Manual Inquiry</DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Source *</Label>
              <Select
                value={formData.source}
                onValueChange={(value) => setFormData({ ...formData, source: value })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="phone">Phone</SelectItem>
                  <SelectItem value="whatsapp">WhatsApp</SelectItem>
                  <SelectItem value="walk-in">Walk-in</SelectItem>
                  <SelectItem value="referral">Referral</SelectItem>
                  <SelectItem value="other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Product Type *</Label>
              <Select
                value={formData.product_type}
                onValueChange={(value) => setFormData({ ...formData, product_type: value, interested_model: "" })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                    <SelectItem value="yutong">Yutong Bus</SelectItem>
                    <SelectItem value="sinotruk">Sinotruck</SelectItem>
                    <SelectItem value="daihatsu">Daihatsu</SelectItem>
                    <SelectItem value="honda">Honda</SelectItem>
                    <SelectItem value="hyundai">Hyundai</SelectItem>
                    <SelectItem value="isuzu">Isuzu</SelectItem>
                    <SelectItem value="kia">KIA</SelectItem>
                    <SelectItem value="mazda">Mazda</SelectItem>
                    <SelectItem value="mitsubishi">Mitsubishi</SelectItem>
                    <SelectItem value="nissan">Nissan</SelectItem>
                    <SelectItem value="perodua">Perodua</SelectItem>
                    <SelectItem value="subaru">Subaru</SelectItem>
                    <SelectItem value="suzuki">Suzuki</SelectItem>
                    <SelectItem value="toyota">Toyota</SelectItem>
                    <SelectItem value="general">General Inquiry</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Customer Name *</Label>
              <Input
                value={formData.customer_name}
                onChange={(e) => setFormData({ ...formData, customer_name: e.target.value })}
                required
              />
            </div>

            <div className="space-y-2">
              <Label>Phone</Label>
              <Input
                value={formData.customer_phone}
                onChange={(e) => setFormData({ ...formData, customer_phone: e.target.value })}
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Email</Label>
              <Input
                type="email"
                value={formData.customer_email}
                onChange={(e) => setFormData({ ...formData, customer_email: e.target.value })}
              />
            </div>

            <div className="space-y-2">
              <Label>Company Name</Label>
              <Input
                value={formData.company_name}
                onChange={(e) => setFormData({ ...formData, company_name: e.target.value })}
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label>Address</Label>
            <Input
              value={formData.address}
              onChange={(e) => setFormData({ ...formData, address: e.target.value })}
            />
          </div>

          <div className="grid grid-cols-3 gap-4">
            <div className="space-y-2">
              <Label>Interested Model</Label>
              <Select
                value={formData.interested_model}
                onValueChange={(value) => setFormData({ ...formData, interested_model: value })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select model" />
                </SelectTrigger>
                <SelectContent>
                  {models?.map((model: any) => (
                    <SelectItem key={model.id} value={model.model_name}>
                      {model.model_name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Quantity</Label>
              <Input
                type="number"
                min="1"
                value={formData.quantity}
                onChange={(e) => setFormData({ ...formData, quantity: parseInt(e.target.value) })}
              />
            </div>

            <div className="space-y-2">
              <Label>Budget Range</Label>
              <Input
                value={formData.budget_range}
                onChange={(e) => setFormData({ ...formData, budget_range: e.target.value })}
                placeholder="e.g., 50M - 100M"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label>Priority</Label>
            <Select
              value={formData.priority}
              onValueChange={(value) => setFormData({ ...formData, priority: value })}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="low">Low</SelectItem>
                <SelectItem value="medium">Medium</SelectItem>
                <SelectItem value="high">High</SelectItem>
                <SelectItem value="urgent">Urgent</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label>Inquiry Message</Label>
            <Textarea
              value={formData.inquiry_message}
              onChange={(e) => setFormData({ ...formData, inquiry_message: e.target.value })}
              placeholder="Any additional details or requirements..."
              rows={4}
            />
          </div>

          <div className="flex justify-end gap-2">
            <Button type="button" variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button type="submit" disabled={createInquiryMutation.isPending}>
              {createInquiryMutation.isPending ? "Creating..." : "Create Inquiry"}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};